name: Main

on:
  push:
    branches: [master]

jobs:
  echo:
    name: Echo
    runs-on: ubuntu-22.04
#    permissions:
#      contents: write
#      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger Workflow in Another Repository
        run: |
          # Set the required variables
          repo_owner="percenuage" 
          repo_name="action"  
          event_type="trigger-workflow" 
          
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"service\": \"toto\", \"version\": \"1\", \"unit\": false, \"integration\": true}}"
      


